<?php return array(
    array(
        'date' => new \DateTime('2003-11-11 10:12:25', new \DateTimeZone('UTC')),
        'name' => 'Foo Company',
        'type' => 'Subscription Payment Sent',
        'currency' => 'GBP',
        'rate' => 1,
        'amount' => -2862,
        'id' => '',
    ),
    array(
        'date' => new \DateTime('2003-11-11 10:12:25', new \DateTimeZone('UTC')),
        'name' => '',
        'type' => 'General Credit Card Deposit',
        'currency' => 'GBP',
        'rate' => 1,
        'amount' => 2862,
        'id' => '',
    ),
    array(
        'date' => new \DateTime('2009-10-22 10:35:33', new \DateTimeZone('UTC')),
        'name' => 'ACME PLC',
        'type' => 'PayPal Express Checkout Payment Sent',
        'currency' => 'GBP',
        'rate' => 1,
        'amount' => -1499,
        'id' => '',
    ),
    array(
        'date' => new \DateTime('2009-10-22 10:35:33', new \DateTimeZone('UTC')),
        'name' => '',
        'type' => 'General Credit Card Deposit',
        'currency' => 'GBP',
        'rate' => 1,
        'amount' => 1499,
        'id' => '',
    ),
);
