<?php return array(
    array(
        'date' => new \DateTime('2013-09-17 09:15:52', new \DateTimeZone('UTC')),
        'name' => 'Americorp',
        'type' => 'PayPal Express Checkout Payment Sent',
        'currency' => 'USD',
        'rate' => 1422 / 2195,
        'amount' => -2195,
        'id' => '',
    ),
    array(
        'date' => new \DateTime('2013-09-17 09:15:52', new \DateTimeZone('UTC')),
        'name' => 'Credit Card',
        'type' => 'Charge from Credit Card',
        'currency' => 'GBP',
        'rate' => 1,
        'amount' => 1422,
        'id' => '',
    ),
    array(
        'date' => new \DateTime('2013-02-08 15:35:58', new \DateTimeZone('UTC')),
        'name' => 'Eurotrash',
        'type' => 'PayPal Express Checkout Payment Sent',
        'currency' => 'EUR',
        'rate' => 885 / 1000,
        'amount' => -1000,
        'id' => '',
    ),
    array(
        'date' => new \DateTime('2013-02-08 15:35:58', new \DateTimeZone('UTC')),
        'name' => 'Credit Card',
        'type' => 'Charge from Credit Card',
        'currency' => 'GBP',
        'rate' => 1,
        'amount' => 885,
        'id' => '',
    ),
    array(
        'date' => new \DateTime('2001-01-01 08:08:08', new \DateTimeZone('UTC')),
        'name' => 'Euro Paid From Balance',
        'type' => 'PayPal Express Checkout Payment Sent',
        'currency' => 'EUR',
        'rate' => 2890 / 3500,
        'amount' => -3500,
        'id' => '',
    ),
);
