name: Build
on:
  push:
    branches: main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (PHP ${{ matrix.php-versions }})
    strategy:
      matrix:
        php-versions:
          - 8.3
          - 8.4
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_extensions: bcmath
      - uses: php-actions/phpunit@v4
        with:
          php_version: ${{ matrix.php-versions }}
          php_extensions: bcmath
