name: Build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (PHP ${{ matrix.php-versions }})
    strategy:
      matrix:
        php-versions:
          - 8.0
          - 8.1
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php-versions }}
          php_extensions: bcmath
